function createfigure(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 29-Mar-2020 10:46:59

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,3,1,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 500]);
box(subplot1,'on');
hold(subplot1,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',15.4);

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create title
title('5 Receivers','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1.5);
set(plot1(1),'DisplayName','S',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot1(2),'DisplayName','R1','Color',[0 0 1]);
set(plot1(3),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(4),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot1(5),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot1(6),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.280204310042135 0.542105254546592 0.0658631056882022 0.165263157894737],...
    'FontSize',12.6);

% Create subplot
subplot2 = subplot(1,3,2,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 500]);
box(subplot2,'on');
hold(subplot2,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',15.4);

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create title
title('7 Receivers','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',1.5);
set(plot2(1),'DisplayName','S',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot2(2),'DisplayName','R1','Color',[0 0 1]);
set(plot2(3),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot2(4),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot2(5),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot2(6),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);
set(plot2(7),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);
set(plot2(8),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);

% Create subplot
subplot3 = subplot(1,3,3,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 500]);
box(subplot3,'on');
hold(subplot3,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',15.4);

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create title
title('9 Receivers','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3,'LineWidth',1.5);
set(plot3(1),'DisplayName','S',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot3(2),'DisplayName','R1','Color',[0 0 1]);
set(plot3(3),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot3(4),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot3(5),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot3(6),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);
set(plot3(7),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);
set(plot3(8),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);
set(plot3(9),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);
set(plot3(10),...
    'Color',[0.803921580314636 0.878431379795074 0.968627452850342]);

