function createfigure(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4, YMATRIX5)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data
%  YMATRIX5:  matrix of y data

%  Auto-generated by MATLAB on 29-Mar-2020 10:37:39

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,5,1,'Parent',figure1,'XTickLabel',{'0','250','500'},...
    'XTick',[0 250 500],...
    'FontSize',12);
box(subplot1,'on');
hold(subplot1,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',13.2);

% Create title
title('R1','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1.5);
set(plot1(1),'DisplayName','100uM');
set(plot1(2),'DisplayName','1mM');
set(plot1(3),'DisplayName','10mM');
set(plot1(4),'DisplayName','100mM');

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.130697528967697 0.670526311036788 0.088403594627809 0.0957894736842105],...
    'FontSize',10.8);

% Create subplot
subplot2 = subplot(1,5,2,'Parent',figure1,'FontSize',12);
box(subplot2,'on');
hold(subplot2,'on');

% Create title
title('R2','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',1.5);
set(plot2(1),'DisplayName','100uM');
set(plot2(2),'DisplayName','1mM');
set(plot2(3),'DisplayName','10mM');
set(plot2(4),'DisplayName','100mM');

% Create subplot
subplot3 = subplot(1,5,3,'Parent',figure1,'FontSize',12);
box(subplot3,'on');
hold(subplot3,'on');

% Create title
title('R3','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3,'LineWidth',1.5);
set(plot3(1),'DisplayName','100uM');
set(plot3(2),'DisplayName','1mM');
set(plot3(3),'DisplayName','10mM');
set(plot3(4),'DisplayName','100mM');

% Create subplot
subplot4 = subplot(1,5,4,'Parent',figure1,'FontSize',12);
box(subplot4,'on');
hold(subplot4,'on');

% Create title
title('R4','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',subplot4,'LineWidth',1.5);
set(plot4(1),'DisplayName','100uM');
set(plot4(2),'DisplayName','1mM');
set(plot4(3),'DisplayName','10mM');
set(plot4(4),'DisplayName','100mM');

% Create subplot
subplot5 = subplot(1,5,5,'Parent',figure1,'FontSize',12);
box(subplot5,'on');
hold(subplot5,'on');

% Create title
title('R5','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot5 = plot(X1,YMatrix5,'Parent',subplot5,'LineWidth',1.5);
set(plot5(1),'DisplayName','100uM');
set(plot5(2),'DisplayName','1mM');
set(plot5(3),'DisplayName','10mM');
set(plot5(4),'DisplayName','100mM');

