function createfigure(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6, YMatrix7, YMatrix8, YMatrix9, YMatrix10, YMatrix11, YMatrix12)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4, YMATRIX5, YMATRIX6, YMATRIX7, YMATRIX8, YMATRIX9, YMATRIX10, YMATRIX11, YMATRIX12)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data
%  YMATRIX5:  matrix of y data
%  YMATRIX6:  matrix of y data
%  YMATRIX7:  matrix of y data
%  YMATRIX8:  matrix of y data
%  YMATRIX9:  matrix of y data
%  YMATRIX10:  matrix of y data
%  YMATRIX11:  matrix of y data
%  YMATRIX12:  matrix of y data

%  Auto-generated by MATLAB on 29-Mar-2020 13:15:18

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(4,3,1,'Parent',figure1,'FontSize',12);
box(subplot1,'on');
hold(subplot1,'on');

% Create ylabel
ylabel('100?M','FontSize',13.2);

% Create title
title('IPTG','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1.5);
set(plot1(1),'DisplayName','R1','Color',[0 0 1]);
set(plot1(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot1(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot1(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.307765442221616 0.83244153573941 0.0535449125477556 0.0728218465539662],...
    'FontSize',10.8);

% Create subplot
subplot2 = subplot(4,3,2,'Parent',figure1,'FontSize',12);
box(subplot2,'on');
hold(subplot2,'on');

% Create title
title('LacI-IPTG','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',1.5);
set(plot2(1),'DisplayName','R1','Color',[0 0 1]);
set(plot2(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot2(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot2(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot2(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot3 = subplot(4,3,3,'Parent',figure1,'FontSize',12);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0 2]);
box(subplot3,'on');
hold(subplot3,'on');

% Create title
title('GFP','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3,'LineWidth',1.5);
set(plot3(1),'DisplayName','R1','Color',[0 0 1]);
set(plot3(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot3(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot3(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot3(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot4 = subplot(4,3,4,'Parent',figure1,'FontSize',12);
box(subplot4,'on');
hold(subplot4,'on');

% Create ylabel
ylabel('1mM','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',subplot4,'LineWidth',1.5);
set(plot4(1),'DisplayName','R1','Color',[0 0 1]);
set(plot4(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot4(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot4(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot4(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot5 = subplot(4,3,5,'Parent',figure1,'FontSize',12);
box(subplot5,'on');
hold(subplot5,'on');

% Create multiple lines using matrix input to plot
plot5 = plot(X1,YMatrix5,'Parent',subplot5,'LineWidth',1.5);
set(plot5(1),'DisplayName','R1','Color',[0 0 1]);
set(plot5(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot5(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot5(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot5(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot6 = subplot(4,3,6,'Parent',figure1,'FontSize',12);
box(subplot6,'on');
hold(subplot6,'on');

% Create multiple lines using matrix input to plot
plot6 = plot(X1,YMatrix6,'Parent',subplot6,'LineWidth',1.5);
set(plot6(1),'DisplayName','R1','Color',[0 0 1]);
set(plot6(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot6(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot6(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot6(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot7 = subplot(4,3,7,'Parent',figure1,'FontSize',12);
box(subplot7,'on');
hold(subplot7,'on');

% Create ylabel
ylabel('10mM','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot7 = plot(X1,YMatrix7,'Parent',subplot7,'LineWidth',1.5);
set(plot7(1),'DisplayName','R1','Color',[0 0 1]);
set(plot7(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot7(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot7(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot7(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot8 = subplot(4,3,8,'Parent',figure1,'FontSize',12);
box(subplot8,'on');
hold(subplot8,'on');

% Create multiple lines using matrix input to plot
plot8 = plot(X1,YMatrix8,'Parent',subplot8,'LineWidth',1.5);
set(plot8(1),'DisplayName','R1','Color',[0 0 1]);
set(plot8(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot8(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot8(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot8(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot9 = subplot(4,3,9,'Parent',figure1,'FontSize',12);
box(subplot9,'on');
hold(subplot9,'on');

% Create multiple lines using matrix input to plot
plot9 = plot(X1,YMatrix9,'Parent',subplot9,'LineWidth',1.5);
set(plot9(1),'DisplayName','R1','Color',[0 0 1]);
set(plot9(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot9(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot9(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot9(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot10 = subplot(4,3,10,'Parent',figure1,'FontSize',12);
box(subplot10,'on');
hold(subplot10,'on');

% Create ylabel
ylabel('100mM','FontSize',13.2);

% Create xlabel
xlabel('Time (min)','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot10 = plot(X1,YMatrix10,'Parent',subplot10,'LineWidth',1.5);
set(plot10(1),'DisplayName','R1','Color',[0 0 1]);
set(plot10(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot10(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot10(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot10(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot11 = subplot(4,3,11,'Parent',figure1,'FontSize',12);
box(subplot11,'on');
hold(subplot11,'on');

% Create xlabel
xlabel('Time (min)','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot11 = plot(X1,YMatrix11,'Parent',subplot11,'LineWidth',1.5);
set(plot11(1),'DisplayName','R1','Color',[0 0 1]);
set(plot11(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot11(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot11(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot11(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

% Create subplot
subplot12 = subplot(4,3,12,'Parent',figure1,'FontSize',12);
box(subplot12,'on');
hold(subplot12,'on');

% Create xlabel
xlabel('Time (min)','FontSize',13.2);

% Create multiple lines using matrix input to plot
plot12 = plot(X1,YMatrix12,'Parent',subplot12,'LineWidth',1.5);
set(plot12(1),'DisplayName','R1','Color',[0 0 1]);
set(plot12(2),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot12(3),'DisplayName','R3',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(plot12(4),'DisplayName','R4',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot12(5),'DisplayName','R5',...
    'Color',[0.678431391716003 0.921568632125854 1]);

