function createfigure(t, y_100uM, y_1mM, y_10mM, y_100mM)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 29-Mar-2020 10:22:52

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 500]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 3.5e-05]);
box(subplot1,'on');
hold(subplot1,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',15.4);

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot1 = plot(t,y_100uM,'Parent',subplot1,'LineWidth',1.5);
set(plot1(1),'Visible','off','DisplayName','S',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot1(2),'DisplayName','R1','Color',[0 0 1]);
set(plot1(3),'DisplayName','R2',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(4),'DisplayName','R3',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot1(5),'DisplayName','R4',...
    'Color',[0.678431391716003 0.921568632125854 1]);
set(plot1(6),'DisplayName','R5',...
    'Color',[0.729411780834198 0.831372559070587 0.95686274766922]);

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.193497626424974 0.782722513089005 0.0790368380501063 0.136998254799302],...
    'FontSize',12.6);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 500]);
box(subplot2,'on');
hold(subplot2,'on');

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot2 = plot(t,y_1mM,'Parent',subplot2,'LineWidth',1.5);
set(plot2(1),'Visible','off',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot2(2),'Color',[0 0 1]);
set(plot2(3),'Color',[0 0.447058826684952 0.74117648601532]);
set(plot2(4),...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot2(5),'Color',[0.678431391716003 0.921568632125854 1]);
set(plot2(6),'Color',[0.729411780834198 0.831372559070587 0.95686274766922]);

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 500]);
box(subplot3,'on');
hold(subplot3,'on');

% Create ylabel
ylabel('IPTG (M)','FontSize',15.4);

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot3 = plot(t,y_10mM,'Parent',subplot3,'LineWidth',1.5);
set(plot3(1),'Visible','off',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot3(2),'Color',[0 0 1]);
set(plot3(3),'Color',[0 0.447058826684952 0.74117648601532]);
set(plot3(4),...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot3(5),'Color',[0.678431391716003 0.921568632125854 1]);
set(plot3(6),'Color',[0.729411780834198 0.831372559070587 0.95686274766922]);

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 500]);
box(subplot4,'on');
hold(subplot4,'on');

% Create xlabel
xlabel('Time (min)','FontSize',15.4);

% Create multiple lines using matrix input to plot
plot4 = plot(t,y_100mM,'Parent',subplot4,'LineWidth',1.5);
set(plot4(1),'Visible','off',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);
set(plot4(2),'Color',[0 0 1]);
set(plot4(3),'Color',[0 0.447058826684952 0.74117648601532]);
set(plot4(4),...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot4(5),'Color',[0.678431391716003 0.921568632125854 1]);
set(plot4(6),'Color',[0.729411780834198 0.831372559070587 0.95686274766922]);

